config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :comments, only: [:index, :create]
    # APIのルーティング追加
    namespace :api do
      resources :comments, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users, through: :members
  has_many :comments
  
  validates :name, presence: true

  def show_last_comment
    if (last_comment = comments.last).present?
      last_comment.content? ? last_comment.content : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end

 end 

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :members
  has_many :groups, through: :members
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  def index
    @comments = Comment.where("id > ? AND group_id Like(?)", "#{params[:id]}", "#{params[:group_id]}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # 未ログインログインページに遷移
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # nameも登録できるようにする
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_group

  def index
    @comment = Comment.new
    @comments = @group.comments.includes(:user)
  end

  def create
    @comment = @group.comments.new(comment_params)

    if @comment.save
      respond_to do |format|
        format.html { redirect_to group_comments_path(@comment.group_id), notice: 'メッセージが送信されました'  }
        format.json
      end

      
    else
      @comments = @group.comments.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_comments_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    # 検索フォームのキーワードであいまい検索を行い、usersテーブルからユーザー情報を取得する
    # 自分の情報は除外する
    @users = User.where('name LIKE(?) AND id NOT LIKE(?)' , "#{params[:keyword]}%", "#{current_user.id}")

    respond_to do |format|
      format.html { redirect_to new_group_path}
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.haml
.content{data: {comment_id: "#{comment.id}" }}
  .content-info
    %p.cotent-info__user
      = comment.user.name
    %p.content-info__date-time
      = comment.created_at.strftime("%Y/%m/%d %H:%M")
  .content__text
    - if comment.content.present?
      = comment.content
  = image_tag comment.image.url, class: 'lower-message__image' if comment.image.present?

app/views/comments/_sidebar.html.haml
.side
  .side-header
    %p.side-header__user-name
      = current_user.name
    %ul.user-menu
      %li.user-menu__create-group
        = link_to new_group_path do
          %i.fa.fa-edit.my-white
      %li.user-menu__edit-user
        = link_to edit_user_path(current_user) do
          %i.fa.fa-cog.my-white

  .group_selection
    - current_user.groups.each do |group|
      = link_to group_comments_path(group) do
        .group_selection__group-name
          = group.name
        .group_selection__group-comment
          = group.show_last_comment

app/views/comments/index.html.haml
= render partial: 'comments/sidebar'

.main
  .main-header
    .current-group
      %p.current-group__group-name
        = @group.name
      %ul.group-members
        Member:
        - @group.users.each do |user|
          %li.group-members__name
            = user.name
    = link_to edit_group_path(@group.id) do
      .main-header__edit-btn
        Edit

  .chat-area
    = render partial: 'comment', collection: @comments
  .form
    -# form_forでのクラス名指定 html:{class: クラス名}
    = form_for [@group, @comment], html: {id: 'new-content', class: 'new-content'} do |f|
      .input-box
        -# = f.text_fieldの次はname属性を設定している。
        = f.text_field :content, class: 'input-box__text', placeholder: 'type a message'
        = f.label :image, class: 'image-label' do
          = fa_icon 'image'
          = f.file_field :image, class: 'image-label__input'
      = f.submit 'Send', class: 'new-content__submit-btn'

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_comments.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_comments.each do |comment|
          %li= comment
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => 'user-search-field'}チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:name => 'search', :placeholder => '追加したいユーザー名を入力してください', :type => 'text' }
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      -# = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      #chat-group-users
        - group.users.each do |user|
          .chat-group-user.clearfix.js-chat-member{:id => "chat-group-user-#{user.id}" }
            %input{:name => 'group[user_ids][]', :type => 'hidden', :value => "#{user.id}"}
            %p.chat-group-user__name= user.name
            - if user.id != current_user.id 
              .user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn{}削除
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
= render partial: 'comments/sidebar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'